name: CI Pipeline

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install git
        run: sudo apt install git -y
      
      - name: Run tests
        run: git --version
